version: '3.9'

services:
  postgres:
    restart: always
    image: postgres:15.2-alpine3.17
    ports:
      - '5432:5432'
    container_name: tz-app-db
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./local-db/001.sql:/docker-entrypoint-initdb.d/001.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  app:
    build: .
    container_name: go-app
    working_dir: /usr/src/app
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./configs:/usr/src/app/configs
      - ./logs:/usr/src/app/logs
      - ./migrations:/usr/src/app/migrations
    ports:
      - "8080:8080"
