bind_add: "8080"
log_level: "error"
log_dir: "./logs/"

storage:
  db_conn_string: "postgres://user:user@tz-app-db:5432/postgres?sslmode=disable"
  db_migrations_url: "postgres://user:user@tz-app-db:5432/postgres?sslmode=disable"
  db_migrations_path: "file://./migrations"